import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { JwtService } from '@nestjs/jwt';
import { DataSource } from 'typeorm';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { AppConfigService } from '../src/config/app-config.service';
import { User } from '../src/modules/auth/entities/user.entity';
import { PlannerProfile } from '../src/modules/wedding-planners/entities/planner-profile.entity';
import { Booking } from '../src/modules/bookings/entities/booking.entity';
import { BookingStatus, ProviderType, UserRole } from '../src/common/enums';

describe('Booking status counts and filtered lists', () => {
  let app: INestApplication;
  let db: DataSource;
  let buyer: User;
  let seller: User;
  let outsider: User;
  let provider: PlannerProfile;
  let buyerToken: string;
  let sellerToken: string;
  let outsiderToken: string;
  const http = () => request(app.getHttpServer());
  const read = (path: string, token = buyerToken) => http().get('/api/bookings' + path).set('Authorization', `Bearer ${token}`);
  const put = (id: string, action: string, token: string, body: object = {}) => http().put(`/api/bookings/${id}/${action}`).set('Authorization', `Bearer ${token}`).send(body);
  const create = () => http().post('/api/bookings').set('Authorization', `Bearer ${buyerToken}`).send({ providerType: 'planner', providerId: provider.id, requirements: 'Plan our wedding celebration', amount: 1000 });
  const assertBuyer = async (expected: object) => expect((await read('/counts').expect(200)).body).toMatchObject(expected);
  beforeAll(async () => {
    const module = await Test.createTestingModule({ imports: [AppModule] }).compile();
    app = module.createNestApplication();
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ transform: true, whitelist: true, forbidNonWhitelisted: true }));
    await app.init();
    db = app.get(DataSource);
    const users = db.getRepository(User);
    const stamp = Date.now();
    const actor = async (role: UserRole, name: string) => users.save(users.create({ role, email: `${name}-${stamp}@gmail.com`, passwordHash: 'unused-fixture', isVerified: true, isActive: true }));
    buyer = await actor(UserRole.BRIDE, 'booking-buyer');
    seller = await actor(UserRole.PLANNER, 'booking-seller');
    outsider = await actor(UserRole.BRIDE, 'booking-outsider');
    provider = await db.getRepository(PlannerProfile).save({ ownerUserId: seller.id, agencyName: 'Count Test Planner', isApproved: true });
    const jwt = new JwtService({ secret: app.get(AppConfigService).auth.jwtSecret });
    buyerToken = jwt.sign({ sub: buyer.id, tv: 0 });
    sellerToken = jwt.sign({ sub: seller.id, tv: 0 });
    outsiderToken = jwt.sign({ sub: outsider.id, tv: 0 });
  }, 90000);
  afterAll(async () => {
    if (db && buyer) await db.getRepository(Booking).delete({ userId: buyer.id });
    if (db && provider) await db.getRepository(PlannerProfile).delete(provider.id);
    for (const actor of [buyer, seller, outsider]) if (db && actor) await db.getRepository(User).delete(actor.id);
    await app?.close();
  });
  it('creates, quotes, accepts, confirms and cancels with immediately consistent counts', async () => {
    await assertBuyer({ all: 0, requested: 0, cancelled: 0 });
    const booking = (await create().expect(201)).body;
    await assertBuyer({ all: 1, requested: 1, quotation: 0 });
    const quote = (await http().post(`/api/bookings/${booking.id}/quotations`).set('Authorization', `Bearer ${sellerToken}`).send({ amount: 1000 }).expect(201)).body;
    await assertBuyer({ all: 1, requested: 0, quotation: 1 });
    expect((await read('?bucket=quotation').expect(200)).body.data.map((b: Booking) => b.id)).toEqual([booking.id]);
    await http().put(`/api/bookings/quotations/${quote.id}/accept`).set('Authorization', `Bearer ${buyerToken}`).send({}).expect(200);
    await put(booking.id, 'confirm', sellerToken).expect(200);
    await assertBuyer({ all: 1, quotation: 0, payment: 1, confirmed: 0 });
    await put(booking.id, 'pay', buyerToken, { milestone: 'advance' }).expect(200);
    await assertBuyer({ all: 1, payment: 0, confirmed: 1, cancelled: 0 });
    await put(booking.id, 'cancel', outsiderToken).expect(403);
    await assertBuyer({ all: 1, confirmed: 1, cancelled: 0 });
    await put(booking.id, 'cancel', buyerToken, { reason: 'Plans changed' }).expect(200);
    await assertBuyer({ all: 1, confirmed: 0, cancelled: 1 });
    expect((await read('?bucket=confirmed').expect(200)).body.meta.total).toBe(0);
    expect((await read('?bucket=cancelled').expect(200)).body.data[0].id).toBe(booking.id);
    expect((await read('/incoming/counts', sellerToken).expect(200)).body).toMatchObject({ all: 1, confirmed: 0, cancelled: 1 });
    expect((await db.getRepository(Booking).findOneByOrFail({ id: booking.id })).status).toBe(BookingStatus.CANCELLED);
    await put(booking.id, 'cancel', buyerToken).expect(400);
    await assertBuyer({ all: 1, cancelled: 1 });
  });
  it('updates in-progress and completed counts throughout delivery and payments', async () => {
    const booking = (await create().expect(201)).body;
    await put(booking.id, 'confirm', sellerToken).expect(200);
    await put(booking.id, 'pay', buyerToken, { milestone: 'advance' }).expect(200);
    await put(booking.id, 'start', sellerToken).expect(200);
    await assertBuyer({ all: 2, confirmed: 0, in_progress: 1, cancelled: 1 });
    await put(booking.id, 'pay', buyerToken, { milestone: 'second' }).expect(200);
    await put(booking.id, 'complete', sellerToken).expect(200);
    await assertBuyer({ all: 2, in_progress: 1, completed: 0 });
    await put(booking.id, 'pay', buyerToken, { milestone: 'final' }).expect(200);
    await put(booking.id, 'confirm-delivery', buyerToken).expect(200);
    await put(booking.id, 'mark-completed', sellerToken).expect(200);
    await assertBuyer({ all: 2, in_progress: 0, completed: 1, cancelled: 1 });
  });
  it('counts the whole database scope and filters before paging', async () => {
    const bookings = db.getRepository(Booking);
    await bookings.save(Array.from({ length: 101 }, () => bookings.create({ userId: buyer.id, bookedByUserId: buyer.id, providerType: ProviderType.PLANNER, providerId: provider.id, status: BookingStatus.REQUESTED })));
    await assertBuyer({ all: 103, requested: 101, cancelled: 1, completed: 1 });
    const first = (await read('?bucket=requested&limit=100&page=1').expect(200)).body;
    const second = (await read('?bucket=requested&limit=100&page=2').expect(200)).body;
    expect(first.data).toHaveLength(100);
    expect(second.data).toHaveLength(1);
    expect(first.meta).toMatchObject({ total: 101, totalPages: 2 });
    const cancelled = (await read('?bucket=cancelled&limit=1').expect(200)).body;
    expect(cancelled.meta.total).toBe(1);
    expect(cancelled.data[0].status).toBe('cancelled');
    const incoming = (await read('/incoming?bucket=requests&limit=100', sellerToken).expect(200)).body;
    expect(incoming.meta.total).toBe(101);
    expect((await read('/incoming/counts', sellerToken).expect(200)).body).toMatchObject({ all: 103, requests: 101, completed: 1, cancelled: 1 });
    expect((await read('/counts', outsiderToken).expect(200)).body.all).toBe(0);
    await http().get('/api/bookings/counts').expect(401);
    await read('?bucket=invalid').expect(400);
  });
});
