import { useState } from 'react';
import { Pressable, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, CaretRight, CheckCircle } from 'phosphor-react-native';

import { api, apiMessage } from '@/lib/api';
import { rupees, shortDate } from '@/lib/format';
import { Alert, Button, Caption, Card, EmptyState, Field, Loading, SectionTitle, Screen } from '@/components/ui';
import { rgb, space, useTheme } from '@/theme';

type Task = { id: string; title: string; category?: string | null; dueDate?: string | null; status: string };
type Timeline = { tasks?: Task[] };
type BudgetData = { budgeted: string; committed: string; categories: { category: string; budgeted: string; committed: string }[] };
type Dashboard = { budget: BudgetData };
type Tab = 'Tasks' | 'Timeline' | 'Budget' | 'Notes';
export default function WeddingPlan() {
  const theme = useTheme(); const router = useRouter(); const qc = useQueryClient(); const { id } = useLocalSearchParams<{ id: string }>(); const [tab, setTab] = useState<Tab>('Tasks'); const [filter, setFilter] = useState('All'); const [adding, setAdding] = useState(false); const [title, setTitle] = useState(''); const [error, setError] = useState('');
  const query = useQuery({ queryKey: ['plan-timeline', id], queryFn: async () => (await api.get(`/planner/plan/${id}/timeline`)).data as Timeline, enabled: Boolean(id), retry: false });
  const dashboard = useQuery({ queryKey: ['wedding-dashboard'], queryFn: async () => (await api.get('/planner/dashboard')).data as Dashboard, retry: false });
  const update = useMutation({ mutationFn: ({ task, status }: { task: Task; status: string }) => api.put(`/planner/tasks/${task.id}/status`, { status }), onSuccess: () => void qc.invalidateQueries({ queryKey: ['plan-timeline', id] }), onError: (e) => setError(apiMessage(e, 'Task could not be updated.')) });
  const add = useMutation({ mutationFn: () => api.post(`/planner/plan/${id}/tasks`, { title, category: 'Custom' }), onSuccess: () => { setTitle(''); setAdding(false); void qc.invalidateQueries({ queryKey: ['plan-timeline', id] }); }, onError: (e) => setError(apiMessage(e, 'Task could not be added.')) });
  if (query.isPending) return <Screen><Loading rows={5} /></Screen>; if (query.error || !query.data) return <Screen><EmptyState title="Wedding plan unavailable">{apiMessage(query.error, 'Please try again shortly.')}</EmptyState></Screen>;
  const data = query.data; const tasks = data.tasks ?? []; const visible = tasks.filter((t) => filter === 'All' || (filter === 'Completed' ? t.status === 'done' : filter === 'To Do' ? t.status === 'pending' : t.status === 'in_progress'));
  return <Screen><View style={{ flexDirection: 'row', alignItems: 'center', gap: space(2) }}><Pressable onPress={() => router.back()}><ArrowLeft size={22} color={rgb(theme.ink[800])} /></Pressable><SectionTitle style={{ flex: 1, textAlign: 'center' }}>Wedding Plan</SectionTitle><View style={{ width: 22 }} /></View><View style={{ flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: rgb(theme.border) }}>{(['Tasks', 'Timeline', 'Budget', 'Notes'] as Tab[]).map((item) => <Pressable key={item} onPress={() => setTab(item)} style={{ paddingVertical: space(2), borderBottomWidth: 2, borderBottomColor: tab === item ? rgb(theme.brand) : 'transparent' }}><Caption tone={tab === item ? 'brand' : 'muted'} style={{ fontWeight: tab === item ? '700' : '400' }}>{item}</Caption></Pressable>)}</View>{error ? <Alert tone="critical">{error}</Alert> : null}
    {tab === 'Tasks' ? <View style={{ gap: space(2) }}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><SectionTitle>Your Checklist</SectionTitle><Caption>{tasks.length} tasks</Caption></View><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: space(1) }}>{['All', 'To Do', 'In Progress', 'Completed'].map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={{ paddingHorizontal: space(2), paddingVertical: space(1), borderRadius: 12, backgroundColor: filter === item ? rgb(theme.brand) : rgb(theme.surfaceSunken) }}><Caption tone={filter === item ? 'onBrand' : 'muted'}>{item}</Caption></Pressable>)}</View>{visible.length ? visible.map((task) => <Pressable key={task.id} disabled={update.isPending} onPress={() => update.mutate({ task, status: task.status === 'done' ? 'pending' : 'done' })}><Card style={{ flexDirection: 'row', alignItems: 'center', padding: space(3) }}><CheckCircle size={21} color={rgb(task.status === 'done' ? theme.brand : theme.ink[400])} weight={task.status === 'done' ? 'fill' : 'regular'} /><View style={{ flex: 1, marginLeft: space(2) }}><Caption style={{ textDecorationLine: task.status === 'done' ? 'line-through' : 'none', color: rgb(theme.ink[800]) }}>{task.title}</Caption><Caption tone="faint">{[task.category, task.dueDate ? shortDate(task.dueDate) : null].filter(Boolean).join(' · ')}</Caption></View><CaretRight size={18} color={rgb(theme.ink[400])} /></Card></Pressable>) : <EmptyState title="No tasks here" />}{adding ? <Card><Field label="Task" value={title} onChangeText={setTitle} placeholder="What needs doing?" /><Button label="Add task" onPress={() => add.mutate()} busy={add.isPending} disabled={!title.trim()} /></Card> : <Button label="Add Custom Task" onPress={() => setAdding(true)} />}</View> : null}
    {tab === 'Timeline' ? <View style={{ gap: space(2) }}><SectionTitle>Planning Timeline</SectionTitle>{tasks.length ? tasks.map((task, index) => <View key={task.id} style={{ flexDirection: 'row', gap: space(3) }}><View style={{ alignItems: 'center' }}><View style={{ width: 18, height: 18, borderRadius: 9, backgroundColor: rgb(theme.brandSoft), borderWidth: 3, borderColor: rgb(theme.brand) }} /><View style={{ flex: 1, width: 1, backgroundColor: rgb(theme.border) }} /></View><View style={{ flex: 1, paddingBottom: space(3) }}><Caption style={{ fontWeight: '700', color: rgb(theme.ink[800]) }}>{task.title}</Caption><Caption tone="faint">{[task.category, shortDate(task.dueDate)].filter(Boolean).join(' · ')}</Caption></View></View>) : <EmptyState title="No milestones yet" />}</View> : null}
    {tab === 'Budget' ? dashboard.isPending ? <Loading rows={3} /> : <Budget budget={dashboard.data?.budget} /> : null}{tab === 'Notes' ? <EmptyState title="Notes are not available yet">The current WOW API does not provide wedding-plan notes, so this mobile screen does not create local-only notes.</EmptyState> : null}
  </Screen>;
}
function Budget({ budget }: { budget?: BudgetData }) { const theme = useTheme(); if (!budget) return <EmptyState title="No budget yet">Budget details appear as bookings and event budgets are added.</EmptyState>; const spent = Number(budget.committed); const total = Number(budget.budgeted); const pct = total ? Math.min(100, Math.round(spent / total * 100)) : 0; return <View style={{ gap: space(3) }}><Card style={{ backgroundColor: rgb(theme.brandSoft) }}><Caption>Total Budget</Caption><SectionTitle>{rupees(total)}</SectionTitle><Caption>Spent {rupees(spent)} · {pct}%</Caption><View style={{ height: 6, backgroundColor: rgb(theme.surface), borderRadius: 4 }}><View style={{ height: 6, width: `${pct}%`, borderRadius: 4, backgroundColor: rgb(theme.brand) }} /></View></Card>{budget.categories.map((c) => <Card key={c.category} style={{ padding: space(3) }}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Caption style={{ textTransform: 'capitalize' }}>{c.category.replace(/_/g, ' ')}</Caption><Caption>{rupees(c.committed)} / {rupees(c.budgeted)}</Caption></View></Card>)}</View>; }
